### ISSUE TITLE
Missed huge spike in existing crash

### ISSUE THREAD

**Issue by amccreight** [mozilla/clouseau#125]
Clouseau seems to have missed bug 1538295, which was a pretty severe increase in the number of crashes in a particular signature that had shown up before. On Nightly, there were 0 crashes in the last month, up until the 20190318133954 build when a huge number of crashes started showing up, particularly considering this is Android Nightly.

**Comment by amccreight** [comment]
It looks like an existing bug, bug 1538295, got reopened on the 18th for this issue, and was closed by the time I noticed it, which might explain why. I'll just close this...

**Comment by calixteman** [comment]
And for info clouseau caught it:
https://bugzilla.mozilla.org/show_bug.cgi?id=1493611#c1

**Comment by amccreight** [comment]
Great! I thought it was bizarre that Clouseau didn't file anything for this, because it usually catches everything. :)
