### ISSUE TITLE
Add a way to get release dates for a given Firefox version in the versions.py module

### ISSUE THREAD

**Issue by marco-c** [mozilla/clouseau#36]
This file contains release dates: http://svn.mozilla.org/libs/product-details/json/firefox_history_major_releases.json

@sylvestre is there another source where we can get info also about upcoming releases?

**Comment by sylvestre** [comment]
https://product-details.mozilla.org/ is better and we can start to use it. 
svn.m.o is going to be decommissioned at some point. 
The upcoming releases are available here: https://wiki.mozilla.org/RapidRelease/Calendar#Future_branch_dates

**Comment by sylvestre** [comment]
we don't have a better alternative but we could consider exporting this into json too.

**Comment by marco-c** [comment]
I've added a function to get the date for a major release in 6b2a22742f311b363fa93f371d936b7758bb0123.

Upcoming dates still missing.

**Comment by marco-c** [comment]
In eca98e813fb8c59384635edcbd982a32de2b8302, I've started using the ICS calendar from https://wiki.mozilla.org/RapidRelease/Calendar#Calendars for future release dates.
