### ISSUE TITLE
Use protocol=2 in auto_mock.py

### ISSUE THREAD

**Issue by marco-c** [mozilla/clouseau#49]
This could result in smaller mock files.

**Comment by La0** [comment]
You mean for the pickle serialization ? At first i tried to use [HIGHEST_PROTOCOL](https://docs.python.org/2/library/pickle.html#pickle.HIGHEST_PROTOCOL), but i had some compatibility issues between Python 2 & 3. I don't think i tried with a specific protocol though

**Comment by marco-c** [comment]
Yes, protocol=2 should be supported by both Python 2 and Python 3.

**Comment by marco-c** [comment]
HIGHEST_PROTOCOL is defined as 2 in Python 2 and an higher number in Python 3, that's why files produced by Python 3 are in a format that Python 2 can't read.

I don't know if using protocol=2 is actually going to make files smaller, since we already compress them, but it's worth trying.
