### ISSUE TITLE
Make Clouseau a library and split the "analysis" and the "clouseau/stability" directories in separate repos

### ISSUE THREAD

**Issue by marco-c** [mozilla/clouseau#51]
I'd like to use clouseau in https://github.com/mozilla/stab-crashes and in https://github.com/marco-c/crashcorrelations, but it's hard if we don't make it a library installable via pip.
- [x] Create separate repository for the library.
- [x] Publish the library on PyPi.
- [x] Make clouseau use the library.

**Comment by marco-c** [comment]
Also, @La0 's work on the backend would be easier if split in another repo where he can simply use clouseau by installing it via pip.

**Comment by La0** [comment]
This is what will happen when the fork of gabras for releng-api is a bit more mature (next week ?)
I don't think the backend branch will ever be merged here (that's why i import in backend "from clouseau ...")

**Comment by marco-c** [comment]
Separate library created: https://github.com/mozilla/libmozdata.

**Comment by marco-c** [comment]
Published on PyPi: https://pypi.python.org/pypi/libmozdata.

**Comment by marco-c** [comment]
Made `clouseau` use `libmozdata` with the latest few commits:
bf6e9b485a115cfd585c9cb12993914917718d8d
edf5f753ab6c00a8ce654480f835931ccd2e451e
72115f507d1ebd416723819ccfc738a2d5157e9d
03bfee740c4f8e1f7e20a1c88504922b91df205c
41d85d7816a42ad69a0990fd67a154c382995245

There might still be fixes needed that I missed (particularly around the configuration file), but the big part is done.
