### ISSUE TITLE
When pushing a comment when updating a flag, we should provide crash numbers for all versions

### ISSUE THREAD

**Issue by sylvestre** [mozilla/clouseau#56]
Example: https://bugzilla.mozilla.org/show_bug.cgi?id=1267692 
Even if the flags are set, as you are pushing a comment anyway, we should add the information in the comment for other releases

**Comment by calixteman** [comment]
Fixed

**Comment by calixteman** [comment]
The commit:
https://github.com/calixteman/clouseau/commit/649ee21c7184ba32c992c28d3cd061d2ff4c890c
