### ISSUE TITLE
clouseau-status-flags - Add some rank information in the reports

### ISSUE THREAD

**Issue by sylvestre** [mozilla/clouseau#72]
Feedback from Jim Mathies:

> For the top rank criteria, simplest thing to do would be to calculate each of the ranks based on the process type (browser, content, plugin). So for example, If it's a browser only crash, content and plugin would be NaN in the report, which is fine. I don't think we need an 'All' process type rating.
> 
> I would also suggest breaking the rankings down by firefox version, similar to the way you do your current crash count tables.

**Comment by calixteman** [comment]
Done in https://github.com/mozilla/clouseau/commit/69ac3148168395e336e52968cebe3d38415e135d
