### ISSUE TITLE
clouseau-status-flags: Don't overwrite people's decisions

### ISSUE THREAD

**Issue by marco-c** [mozilla/clouseau#73]
E.g. in bug 1288997, I set firefox49 as 'unaffected' and firefox50 as 'affected' because it was a regression in Firefox 50.
The bot reset firefox49 to 'affected'.

The bot shouldn't overwrite the decision of humans in these cases. It could 1) just comment and let the people in the bug decide whether they want to change a status flag; 2) add a needinfo? to the person who set the status flag to ask him/her if he/she wants to change it.

**Comment by calixteman** [comment]
Done in https://github.com/mozilla/clouseau/commit/69ac3148168395e336e52968cebe3d38415e135d.
Right now, the fix consists to not change the status flag when someone in the past changed it from 'affected' to 'unaffected'.

**Comment by calixteman** [comment]
sorry read 'affected' to 'unaffected'
