### ISSUE TITLE
 clouseau-status-flags - Do not update when release is tiny 

### ISSUE THREAD

**Issue by sylvestre** [mozilla/clouseau#87]
https://bugzilla.mozilla.org/show_bug.cgi?id=1303967#c9
With 3 crashes, not sure it was worth updating it

**Comment by marco-c** [comment]
This could also help with false positives. The problem is deciding what is the minimum number of crashes that we should consider important enough.

**Comment by marco-c** [comment]
I've seen a few more cases of this today.

**Comment by calixteman** [comment]
Fixed in commit #107
