### ISSUE TITLE
clouseau-status-flags - wrong bug picked for EMPTY: no crashing thread identified; ERROR_NO_MINIDUMP_HEADER

### ISSUE THREAD

**Issue by marco-c** [mozilla/clouseau#88]
https://bugzilla.mozilla.org/show_bug.cgi?id=1113145#c18

I'm not sure how to detect this case. The signature covers a lot of different crashes, the bug
is a specific crash.

**Comment by marco-c** [comment]
Maybe the best option is to ignore the catch-all signatures ("OOM | small" and "EMPTY: no crashing thread identified; ERROR_NO_MINIDUMP_HEADER").

**Comment by marco-c** [comment]
Another signature that is really generic is `AsyncShutdownTimeout | quit-application-granted |
SessionStore: flushing all windows`.

The bot picked https://bugzilla.mozilla.org/show_bug.cgi?id=1305726, but it's not the right bug (that bug covers a really specific crash).

**Comment by calixteman** [comment]
I added a list of ignored signatures in clouseau.ini file.

**Comment by marco-c** [comment]
Great!
